services:
  db:
    image: postgres:15beta1
    volumes:
      - db-data:/var/lib/postgresql/data
    # environment:
    #   - POSTGRES_DB=postgres
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
    env_file:
      - .env

volumes:
  db-data:
  files-data:
